# Generated by Django 2.0.7 on 2018-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParseMaxRowCount', models.IntegerField()),
                ('MySQLTotalExecutionCounts', models.IntegerField()),
                ('SQLId', models.BigIntegerField()),
                ('SQLText', models.CharField(default='', max_length=200)),
                ('MaxLockTime', models.IntegerField()),
                ('ReturnTotalRowCounts', models.IntegerField()),
                ('SQLIdStr', models.CharField(default='', max_length=50)),
                ('TotalLockTimes', models.IntegerField()),
                ('MaxExecutionTime', models.IntegerField()),
                ('CreateTime', models.DateField()),
                ('SlowLogId', models.CharField(default='', max_length=50)),
                ('ParseTotalRowCounts', models.IntegerField()),
                ('MySQLTotalExecutionTimes', models.IntegerField()),
                ('DBName', models.CharField(default='', max_length=50)),
                ('ReturnMaxRowCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SlowLogOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MySQLTotalExecutionCounts', models.IntegerField()),
                ('MaxLockTime', models.IntegerField()),
                ('SQLText', models.CharField(default='', max_length=200)),
                ('ReturnTotalRowCounts', models.IntegerField()),
                ('ParseTotalRowCounts', models.IntegerField()),
                ('MySQLTotalExecutionTimes', models.IntegerField()),
                ('DBName', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField()),
                ('content', models.CharField(default='', max_length=200)),
                ('createtime', models.DateTimeField()),
                ('distributor', models.CharField(default='', max_length=100)),
                ('executor', models.CharField(default='', max_length=100)),
                ('updatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SQLId', models.BigIntegerField()),
                ('ReturnRowCounts', models.IntegerField()),
                ('HostAddress', models.CharField(default='', max_length=100)),
                ('SQLText', models.CharField(default='', max_length=200)),
                ('LockTimes', models.IntegerField()),
                ('ExecutionStartTime', models.DateTimeField()),
                ('ParseRowCounts', models.IntegerField()),
                ('QueryTimes', models.IntegerField()),
                ('DBName', models.CharField(default='mysql', max_length=50)),
            ],
        ),
    ]
