# Generated by Django 2.0.7 on 2019-01-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowlog',
            name='SQLText',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slowlogorder',
            name='SQLText',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slowlogorder',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slowrecord',
            name='SQLText',
            field=models.TextField(),
        ),
    ]
