# Generated by Django 2.0.7 on 2019-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowquery', '0002_auto_20190102_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowLogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowid', models.IntegerField()),
                ('content', models.TextField()),
                ('commentor', models.CharField(default='', max_length=50)),
                ('createtime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='slowlog',
            name='slow_status',
            field=models.IntegerField(default=0),
        ),
    ]
